version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: dockerfile-php
    image: php/7.2-fpm
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./www/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

#Docker Networks

networks:
  app-network:
        driver: bridge
